config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :searchs, only: :index
  resources :users
  resources :categories
  resources :posts do
    resources :comments do
      member do
        get :reply
      end
    end
    resources :rates
    resources :likes
  end
  resources :comments do
    resources :comments
  end
  namespace :admin do
    root "comments#new"
    resources :posts
    resources :comments
  end
  get "*path", to: redirect("/")
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user, presence: true
  validates :post, presence: true
  def liked? post_id
    current_user.likes.find_by(post_id: post_id).present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :load_post
  before_action :authenticate_user!

  def create
    unless liked? @post.id
      @like = current_user.likes.build
      @like.post = @post
    end
    respond_to {|format| format.js} if @like.save
  end

  def destroy
    @like = Like.find_by id: params[:id]
    respond_to {|format| format.js} if @like.destroy
  end

  private

  def load_post
    @post = Post.find_by id: params[:post_id]
    load_info @post
  end
end

app/views/likes/_like.html.slim
= post.likes.size
= " "
= link_to fa_icon("heart-o"), post_likes_path(post), method: :post, remote: true,
rel: "tooltip",title: t(".like"), class: "text-dark"

app/views/likes/_unlike.html.slim
= post.likes.size
= " "
= link_to fa_icon("heart"), post_like_path(post, current_user.likes.find_by(post_id: post.id)),
method: :delete, remote: true,rel: "tooltip", title: t(".unlike")