config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :searchs, only: :index
  resources :users
  resources :categories
  resources :posts do
    resources :comments do
      member do
        get :reply
      end
    end
    resources :rates
    resources :likes
  end
  resources :comments do
    resources :comments
  end
  namespace :admin do
    root "comments#new"
    resources :posts
    resources :comments
  end
  get "*path", to: redirect("/")
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :rates, dependent: :destroy
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true
  validates :user, presence: true
  validates :category, presence: true
  enum status: %i(watting approved rejected)
  mount_uploader :picture, PictureUploader
  delegate :name, to: :category, prefix: true, allow_nil: true
  scope :sort_by_updated, -> {order(updated_at: :asc)}
  scope :post_filter, ->{where("status = ?", "1")}
  scope :admin_filter_category, -> (category_id){includes(:category).where(category_id: category_id)}
  scope :show_post_host,
   -> {select("posts.*, avg(rates.star) as average_rate, count(rates.id) as number_of_rate ")
    .joins(:rates).where("posts.created_at >= ? and posts.updated_at >= ? ",
     Date.today.beginning_of_week, Date.today.beginning_of_week)
    .group("posts.id").order("average_rate DESC").limit(3)}

  scope :show_blog_category_interested,
    ->{select("posts.*, avg(rates.star) as average_rate, count(rates.id) as number_of_rate ")
    .joins(:rates)
    .group("posts.id").order("average_rate DESC").limit(3)}
end

app/models/supports/post.rb
class Supports::Post
  attr_reader :post, :posts

  def initialize post
    @post = post
  end

  def posts
    @posts ||= Post.all
  end
  def comment
    @comment = Comment.new
  end

  def comments_tree
    @comments = @post.comments
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :load_post, only: %i(show update destroy)

  def index
    @posts = Post.sort_by_updated.page(params[:page]).per 10
  end

  def show
  end

  def update
    if @post.update_attributes post_params
      flash[:success] = t ".update_success"
    else
      flash[:danger] = t "update_failed"
    end
    redirect_to admin_posts_path @post
  end

  def destroy
    if @post.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit :status
  end

  def load_post
    @post = Post.find_by id: params[:id]
    load_info @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :load_post, except: %i(create new index)

  def index
    @search = Post.ransack params[:q]
    @search.sorts = Settings.default_sort if @search.sorts.empty?
    @posts = @search.result.post_filter.joins(:category)
    .page(params[:page]).per 10
    @post_hostest_week =  Post.post_filter.show_post_host
    @category_relates = Post.post_filter.show_blog_category_interested
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = t ".create_post"
      redirect_to @post
    else
      render :new
    end

  end

  def edit; end

  def update
    @post.update_attributes post_params
    if @post.save
      flash[:success] = t ".update_success"
      redirect_to @post
    else
      render :edit
    end
  end

  def show
    @rates = @post.rates
    @supports = Supports::Post.new @post
  end

  def destroy
    if @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.js { head :no_content }
      end
    else
      flash[:danger] = t ".failed_delete"
      redirect_to root_url
    end
  end

  private

  def post_params
    params.require(:post).permit :title, :content, :picture,
     :picture_cache, :category_id
  end

  def load_post
    @post = Post.find_by id: params[:id]
    load_info @post
  end
end

app/views/posts/_form_post.html.slim
= form_for @post do |f|
  = render "shared/error_messages", object: f.object
  .form-group
    = f.label :title
    = f.text_field :title, placeholder: "Title", class: "form-control"
    = f.label :category_id,  t(".category")
    = f.select :category_id, Category.all.pluck(:name, :id), {}, { class: "selectize"}
    = f.label :content
    = f.text_area :content,placeholder: "Content. . .", class: "form-control", rows: 7, cols: 50
    = f.label :picture
    = f.file_field :picture, accept: "image/jpeg,image/gif,image/png"
    = f.submit @post.new_record? ? t(".create") : t(".update"), class: "btn btn-primary btn-create"
  .error_category
.modal.fade.category-modal[tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"]
  .modal-dialog.modal-sm[role="document"]
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
        h4#mySmallModalLabel.modal-title
          | Add Category
      .modal-body
        = form_for Category.new , remote: true do  |f|
          .form-group
            = f.label :name
            = f.text_field :name, class: "form-control category_name"
            = f.submit class: "btn btn-primary"

app/views/posts/_post.html.slim
div id="post-#{post.id}"
  .host-post
    h2.card-title
      = link_to post.title.capitalize, post
    p.post-meta
      = "Posted by "
      = post.user.name
      = " on "
      = post.updated_at.strftime(Settings.post.date)
    .image-post
      = link_to image_tag(post.picture.url, class: "img-thumbnail"), post
    h3.card-body
      = truncate post.content
    - image = post.user.avatar.present? ? post.user.avatar.url : "cat.jpg"
    = image_tag(image, class: "avatar-post")
    p
      = social_share_button_tag(post.title, url: "https://safe-retreat-68629.herokuapp.com", desc: post.content)
    .col-md-1 id="btn-like-#{post.id}"
      - if user_signed_in? && liked?(post.id)
        = render partial: "likes/unlike", locals: {post: post}
      - else
        = render partial: "likes/like", locals: {post: post}
    span.glyphicon.glyphicon-comment
    - if post.user == current_user
      = link_to edit_post_path(post) do
        span.glyphicon.glyphicon-pencil
      = " "
      = link_to post, method: :delete, data: {confirm: t(".sure")} do
        span.glyphicon.glyphicon-remove
hr

app/views/posts/_post_hostest_week.html.slim
h3.card-title
  = link_to post.title, post
h4.post-meta
  = simple_format(truncate(post.content, length: 100))
  - @average_rate = rating post
| <p class="average-review-rating" data-score=
= @average_rate
| >
hr

app/views/posts/_review_form.html.slim
#review_post.modal.fade aria-hidden="true" aria-labelledby="reviewpostLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5#reviewpostLabel.modal-title
          = t ".rate", name: @post.title.capitalize
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
         = form_for :rate,  url: post_rates_path(@post),remote: true, method: :post do |f|
          .rate_error
          .star_content
            label
              = t ".quantity"
            .form-group
              =f.hidden_field :star, value: 5
              - 5.times do |i|
                div class=("star #{"star_on" if i + 1 == 1}")
                  i.fa.fa-star value=("#{i + 1}")
            .form-group
              label.form-control-label= t ".comment"
              = f.cktext_area :content, class: "form-control"
            .form-group
              = f.button t(".submit"), type: :submit, class: "btn-custom2"

app/views/posts/edit.html.slim
- provide :button_text, t(".save")
.yield
  h1
    = t ".update_post"
  .row
    .col-md-8.col-md-offset-2
      =  render "form_post"

app/views/posts/index.html.slim
.container
  .row
    .col-lg-8.col-md-10
      - if @posts.any?
        .post-preview
          = render partial: "posts/post", collection: @posts, as: :post
    .col-lg-4.col-md-2
      .host-post
        h1
          = "Post"
          = render partial: "post_hostest_week", collection: @post_hostest_week, as: :post
      br
      .host-post
        h1
          = "Category"
          = render partial: "post_hostest_week", collection:  @category_relates, as: :post
#infinite-scrolling
  = paginate @posts,theme: 'twitter-bootstrap-3'

app/views/posts/new.html.slim
- provide :button_text, t(".post")
.container
  h1
    = t(".create_post")
  .row
    .col-md-8.col-md-offset-2
      = render "form_post"

app/views/posts/show.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      .host-post
        .post-heading.word-break
          h2
            = @post.title.capitalize
          = image_tag @post.user.avatar.url, class: "avatar-post"
          span.meta
            = @post.updated_at.strftime("%B %e, %Y at %I:%M %p")
          - if @post.category.present?
            span
              i.fa.fa-tags
              = t ".category"
              | :
              span.badge.badge-info
                = link_to @post.category_name, @post.category
          br
          .image-post
            = image_tag(@post.picture.url, class: "img-thumbnail")
          p
            = simple_format @post.content
          span
          - if @post.user == current_user
            = link_to t(".edit_post"), edit_post_path(@post),
                           class: "btn btn-primary button_text profile"
            = link_to t(".delete"), @post, method: :delete,
                           data: {confirm: t(".sure")}, class: "btn btn-danger button_text profile"
hr
article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .host-post
          / - @average_rate = rating @post
          / | <div class="average-review-rating" data-score=
          / = @average_rate
          / | >
          / small.col-md-2 id="btn-like-#{@post.id}"
          /   - if user_signed_in? && liked?(@post.id)
          /     = render partial: "likes/unlike", locals: {post: @post}
          /   - else
          /     = render partial: "likes/like", locals: {post: @post}
          /   = social_share_button_tag(@post.title, url:"https://safe-retreat-68629.herokuapp.com", desc: @post.content)
          = render "comments/widget", commentable: @post
          .group-tabs
            ul.nav.nav-tabs role="tablist"
              li.active role="presentation"
                a aria-controls="review" data-toggle="tab" href="#review" role="tab"  Review
              li role="presentation"
                a aria-controls="description" data-toggle="tab" href="#description" role="tab"  Description
            .tab-content
              #review.tab-pane.active role="tabpanel"
                - if user_signed_in?
                  = render "review_form"
                  = link_to "add review", "#review_post", data: {toggle: "modal", target: "#review_post"}, class: "btn btn-custom2"
                .show_rates
                  = render partial: "rates/rate", collection: @rates, as: :rate
              #description.tab-pane role="tabpanel" Description