config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :searchs, only: :index
  resources :users
  resources :categories
  resources :posts do
    resources :comments do
      member do
        get :reply
      end
    end
    resources :rates
    resources :likes
  end
  resources :comments do
    resources :comments
  end
  namespace :admin do
    root "comments#new"
    resources :posts
    resources :comments
  end
  get "*path", to: redirect("/")
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :star, presence: true, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  validates :content, presence: true,
   length: {maximum: 100}
  delegate :name, to: :user, prefix: true, allow_nil: true

end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :load_post
  before_action :load_rate, only: %i(edit update destroy)
  before_action :authenticate_user!, only: %i(new edit)

 def new
    @rate = Rate.new
 end

 def create
    @rate = current_user.rates.build rate_params
    @rate.post_id = params[:post_id]
    if @rate.save
      flash[:success] = t ".save_success"
      redirect_to @post
    else
      respond_to {|format| format.js }
    end
 end

 def edit; end

 def update
  @rate.update_attributes rate_params
  if @rate.save
    flash[:success] = t ".update_success"
    redirect_to @post
  else
    render :edit
  end
 end

 private

 def load_post
   @post = Post.find_by id: params[:post_id]
   load_info @post
 end

 def load_rate
    @rate = Rate.find_by id: params[:id]
    load_info @rate
 end

 def rate_params
   params.require(:rate).permit :star, :content
 end
end

app/views/rates/_rate.html.slim
.rate_user.well
  = image_tag rate.user.avatar.url if rate.user.avatar.present?
  p.post-title
    = rate.user.name
  p.post-meta
    = rate.updated_at.strftime(Settings.post.date)
  blockquote
    = rate.content
  .rate_star
    - 5.times do |i|
      div class=("star #{"star_on" if i < rate.star}")
        i.fa.fa-star
  - if rate.user == current_user
    = link_to "edit", edit_post_rate_path(rate.post, rate), class: "text-primary edit-comment"

app/views/rates/edit.html.slim
.col-md-6.col-md-offset-3
  .edit-review-form
    h1 = t(".edit_rate")
    = form_for([@post, @rate]) do |f|
      #rating-form
        label Rating
      .form-group
        label.form-control-label= t ".comment"
        = f.cktext_area :content, class: "form-control"
      .form-group
        = f.button "update", type: :submit, class: "btn-custom2"