config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"

  resources :searchs, only: :index
  resources :users
  resources :categories
  resources :posts do
    resources :comments do
      member do
        get :reply
      end
    end
    resources :rates
    resources :likes
  end
  resources :comments do
    resources :comments
  end
  namespace :admin do
    root "comments#new"
    resources :posts
    resources :comments
  end
  get "*path", to: redirect("/")
end

app/views/layouts/_footer.html.slim
footer.footer
  small.text-center
    = "Copyright © spensation 2018"

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to ("Blog"), root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          = link_to ("Post"), posts_path
        li
          = link_to ("User"), users_path
          span.sr-only (current)
        li
          = link_to ("Category"), categories_path

      form.navbar-form.navbar-left
        .form-group
          = search_form_for @search, url: posts_path do |f|
            = f.text_field :title_or_content_cont,placeholder: "Search post...", class: "form-control"
            = f.collection_select :category_id_eq, Category.order(:name), :id, :name, class: "form-control"
            = f.button "search", type: :submit, class: "btn-custom2"
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to t(".create_post"), new_post_path, class: "btn btn-small"
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              = current_user.name
              span.caret
            ul.dropdown-menu
              li
                = link_to "My post",  current_user
              li
                = link_to "Profile", edit_user_registration_path(current_user)
              li
                = link_to "logout", destroy_user_session_path, method: :delete
        - else
            li
              = link_to t(".signup"), "#signup", data: {toggle: "modal", target: "#signup"}, class: "btn btn-small"
            li
              = link_to t(".login"), "#login", data: {toggle: "modal", target: "#login"}, class: "btn btn-small"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta content="width=device-width, initial-scale=1.0" name="viewport"
  body
    = render "layouts/header"
    = render "shared/flash"
    = render "devise/registrations/new"
    = render "devise/sessions/new"
    = yield
    = render "layouts/footer"